encoding: utf-8
safe: true

baseurl: /trillek-computer

# Sets to use GitHub Markdown variant
markdown:      kramdown
markdown_ext:  md

kramdown:
  input: GFM
  hard_wrap: false

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [.travis.yml, package.json, lib]

