encoding: utf-8
safe: true

# Sets to use GitHub Markdown variant
markdown:      kramdown
markdown_ext:  md

kramdown:
  input: GFM

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [.travis.yml, package.json, grunt.js, Gruntfile.js, node_modules]

